provider "aws" {
  region = "ap-south-1"
}

resource "aws_instance" "public-web-ec2" {
  ami                         = "ami-0cda377a1b884a1bc"
  instance_type               = "t3a.micro"
  availability_zone           = "ap-south-1a"
  key_name                    = "Task"
  subnet_id                   = "subnet-019d14a13c07a30c5"
  vpc_security_group_ids      = ["sg-0730e1c4f2a1c04fd"]
  associate_public_ip_address = true

}

resource "local_file" "tf_ansible_vars_file_new" {
  content  = <<-DOC
    # Ansible vars_file containing variable values from Terraform.
    # Generated by Terraform mgmt configuration.

    tf_public_dns_name: ${aws_instance.public-web-ec2.public_dns}
    tf_public_ip: ${aws_instance.public-web-ec2.public_ip}
    DOC
  filename = "./tf_ansible_vars_file.yml"
}