---
  - name: "Create ec2"
    hosts: localhost
    connection: local   
    gather_facts: false
    tasks:
    - name: Creating ec2 instance
      ec2:
        region: ap-south-1
        key_name: Task
        instance_type: t3a.micro
        image: ami-04bde106886a53080
        wait: yes
        wait_timeout: 500
        count: 1
        monitoring: no
        vpc_subnet_id: subnet-019d14a13c07a30c5
        assign_public_ip: yes

    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day
    
    - name: Install Java using Ansible
      become: yes
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
           - openjdk-11-jdk
