---
  - name: "Create ec2"
    hosts: localhost
    connection: local   
    gather_facts: false
    tasks:
    - name: Creating ec2 instance
      ec2:
        region: ap-south-1
        key_name: Task
        instance_type: t3a.micro
        image: ami-04bde106886a53080
        wait: yes
        wait_timeout: 500
        count: 1
        monitoring: no
        vpc_subnet_id: subnet-019d14a13c07a30c5
        assign_public_ip: yes

    - name: install java
      become: true
      apt:
        update_cache: yes
    
    - name: Install OpenJDK Java
      become: yes
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        openjdk-8-jdk